spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UncleCatMySelf/config-repo
          username: yourName
          password: yourPassword
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
server:
  port: 9084