eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
# 修改链接名称
#  instance:
#    hostname: clientName
spring:
  application:
    name: client-one
server:
  port: 9081